(cl:defpackage bt_follow-msg
  (:use )
  (:export
   "<FOLLOWACTION>"
   "FOLLOWACTION"
   "<FOLLOWACTIONFEEDBACK>"
   "FOLLOWACTIONFEEDBACK"
   "<FOLLOWACTIONGOAL>"
   "FOLLOWACTIONGOAL"
   "<FOLLOWACTIONRESULT>"
   "FOLLOWACTIONRESULT"
   "<FOLLOWFEEDBACK>"
   "FOLLOWFEEDBACK"
   "<FOLLOWGOAL>"
   "FOLLOWGOAL"
   "<FOLLOWRESULT>"
   "FOLLOWRESULT"
  ))

