; Auto-generated. Do not edit!


(cl:in-package bt_follow-msg)


;//! \htmlinclude FollowGoal.msg.html

(cl:defclass <FollowGoal> (roslisp-msg-protocol:ros-message)
  ((task
    :reader task
    :initarg :task
    :type cl:string
    :initform ""))
)

(cl:defclass FollowGoal (<FollowGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bt_follow-msg:<FollowGoal> is deprecated: use bt_follow-msg:FollowGoal instead.")))

(cl:ensure-generic-function 'task-val :lambda-list '(m))
(cl:defmethod task-val ((m <FollowGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bt_follow-msg:task-val is deprecated.  Use bt_follow-msg:task instead.")
  (task m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowGoal>) ostream)
  "Serializes a message object of type '<FollowGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'task))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'task))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowGoal>) istream)
  "Deserializes a message object of type '<FollowGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'task) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'task) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowGoal>)))
  "Returns string type for a message object of type '<FollowGoal>"
  "bt_follow/FollowGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowGoal)))
  "Returns string type for a message object of type 'FollowGoal"
  "bt_follow/FollowGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowGoal>)))
  "Returns md5sum for a message object of type '<FollowGoal>"
  "0ece8f504419f7ca4d91b277e47ff617")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowGoal)))
  "Returns md5sum for a message object of type 'FollowGoal"
  "0ece8f504419f7ca4d91b277e47ff617")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowGoal>)))
  "Returns full string definition for message of type '<FollowGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string task~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowGoal)))
  "Returns full string definition for message of type 'FollowGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string task~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'task))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowGoal
    (cl:cons ':task (task msg))
))
