(cl:defpackage ur_vision_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX2D>"
   "BOUNDINGBOX2D"
   "<DETECTEDOBJECT2D>"
   "DETECTEDOBJECT2D"
   "<DETECTEDOBJECTARRAY2D>"
   "DETECTEDOBJECTARRAY2D"
   "<TRACKEDOBJECT2D>"
   "TRACKEDOBJECT2D"
   "<TRACKEDOBJECTARRAY2D>"
   "TRACKEDOBJECTARRAY2D"
  ))

