// Generated by gencpp from file following/FollowResult.msg
// DO NOT EDIT!


#ifndef FOLLOWING_MESSAGE_FOLLOWRESULT_H
#define FOLLOWING_MESSAGE_FOLLOWRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace following
{
template <class ContainerAllocator>
struct FollowResult_
{
  typedef FollowResult_<ContainerAllocator> Type;

  FollowResult_()
    : state()  {
    }
  FollowResult_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::following::FollowResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::following::FollowResult_<ContainerAllocator> const> ConstPtr;

}; // struct FollowResult_

typedef ::following::FollowResult_<std::allocator<void> > FollowResult;

typedef boost::shared_ptr< ::following::FollowResult > FollowResultPtr;
typedef boost::shared_ptr< ::following::FollowResult const> FollowResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::following::FollowResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::following::FollowResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::following::FollowResult_<ContainerAllocator1> & lhs, const ::following::FollowResult_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::following::FollowResult_<ContainerAllocator1> & lhs, const ::following::FollowResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::following::FollowResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::following::FollowResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::following::FollowResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::following::FollowResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::following::FollowResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::following::FollowResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::following::FollowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::following::FollowResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::following::FollowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "following/FollowResult";
  }

  static const char* value(const ::following::FollowResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::following::FollowResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"string state\n"
;
  }

  static const char* value(const ::following::FollowResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::following::FollowResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::following::FollowResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::following::FollowResult_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOWING_MESSAGE_FOLLOWRESULT_H
