; Auto-generated. Do not edit!


(cl:in-package following-msg)


;//! \htmlinclude FollowResult.msg.html

(cl:defclass <FollowResult> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:string
    :initform ""))
)

(cl:defclass FollowResult (<FollowResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name following-msg:<FollowResult> is deprecated: use following-msg:FollowResult instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <FollowResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader following-msg:state-val is deprecated.  Use following-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowResult>) ostream)
  "Serializes a message object of type '<FollowResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'state))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowResult>) istream)
  "Deserializes a message object of type '<FollowResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'state) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'state) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowResult>)))
  "Returns string type for a message object of type '<FollowResult>"
  "following/FollowResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowResult)))
  "Returns string type for a message object of type 'FollowResult"
  "following/FollowResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowResult>)))
  "Returns md5sum for a message object of type '<FollowResult>"
  "af6d3a99f0fbeb66d3248fa4b3e675fb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowResult)))
  "Returns md5sum for a message object of type 'FollowResult"
  "af6d3a99f0fbeb66d3248fa4b3e675fb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowResult>)))
  "Returns full string definition for message of type '<FollowResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowResult)))
  "Returns full string definition for message of type 'FollowResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%string state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'state))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowResult
    (cl:cons ':state (state msg))
))
