// Generated by gencpp from file bt_follow/FollowGoal.msg
// DO NOT EDIT!


#ifndef BT_FOLLOW_MESSAGE_FOLLOWGOAL_H
#define BT_FOLLOW_MESSAGE_FOLLOWGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bt_follow
{
template <class ContainerAllocator>
struct FollowGoal_
{
  typedef FollowGoal_<ContainerAllocator> Type;

  FollowGoal_()
    : task()  {
    }
  FollowGoal_(const ContainerAllocator& _alloc)
    : task(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type;
  _task_type task;





  typedef boost::shared_ptr< ::bt_follow::FollowGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bt_follow::FollowGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowGoal_

typedef ::bt_follow::FollowGoal_<std::allocator<void> > FollowGoal;

typedef boost::shared_ptr< ::bt_follow::FollowGoal > FollowGoalPtr;
typedef boost::shared_ptr< ::bt_follow::FollowGoal const> FollowGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bt_follow::FollowGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bt_follow::FollowGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bt_follow::FollowGoal_<ContainerAllocator1> & lhs, const ::bt_follow::FollowGoal_<ContainerAllocator2> & rhs)
{
  return lhs.task == rhs.task;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bt_follow::FollowGoal_<ContainerAllocator1> & lhs, const ::bt_follow::FollowGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bt_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bt_follow::FollowGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bt_follow::FollowGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bt_follow::FollowGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bt_follow::FollowGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bt_follow::FollowGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bt_follow::FollowGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bt_follow::FollowGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ece8f504419f7ca4d91b277e47ff617";
  }

  static const char* value(const ::bt_follow::FollowGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ece8f504419f7caULL;
  static const uint64_t static_value2 = 0x4d91b277e47ff617ULL;
};

template<class ContainerAllocator>
struct DataType< ::bt_follow::FollowGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bt_follow/FollowGoal";
  }

  static const char* value(const ::bt_follow::FollowGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bt_follow::FollowGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string task\n"
;
  }

  static const char* value(const ::bt_follow::FollowGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bt_follow::FollowGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bt_follow::FollowGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bt_follow::FollowGoal_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BT_FOLLOW_MESSAGE_FOLLOWGOAL_H
